[project]
name = 'succotash'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.file_indexing]
path = 'contracts/file_indexing.clar'
clarity_version = 2
epoch = 2.5

[contracts.timed_withdrawal_wallet]
path = 'contracts/timed_withdrawal_wallet.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
